### ISSUE TITLE
Investigate lockfile root cause: tsx/get-tsconfig hoisting regression from PR #398

### ISSUE THREAD

**Issue by dmays-newb** [aptx-health/ripit-fitness#416]
## Context

PR #398 (weekly dep updates) broke staging — the migrate init container failed with:

\`\`\`
Cannot find module /app/node_modules/get-tsconfig/dist/index.cjs
\`\`\`

This was unblocked by #415, which explicitly installs \`get-tsconfig\` and \`esbuild\` in the runner stage of the Dockerfile. **That fix masks the underlying issue rather than addressing it.**

## What to investigate

- Why does \`npm install tsx@4.19.4\` in the runner stage no longer pull \`get-tsconfig\` to the expected hoisted path after PR #398?
- Likely an npm dedupe/hoisting quirk triggered by the dep bumps in #398
- Reproduce by reverting #415 and rebuilding the Docker image

## Possible fixes once root cause is known

- Clean-rebuild the lockfile
- Pin a known-good resolution
- Move \`scripts/sync-exercise-data.ts\` off \`tsx\` to compiled JS so the runner stage doesn't need a TS runtime at all (probably the cleanest long-term fix)

## References

- Broken PR: #398
- Unbreak fix: #415
